language: minimal
dist: xenial
matrix:
  include:
    - os: linux
      env: NVIM_VERSION=stable
    - os: linux
      env: NVIM_VERSION=unstable
    - os: osx
  allow_failures:
    - os: linux
      env: NVIM_VERSION=unstable
before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    brew update
    brew install neovim pandoc luarocks
  else
    sudo add-apt-repository -y ppa:neovim-ppa/$NVIM_VERSION
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends neovim pandoc luarocks
  fi
  luarocks --local install busted
install: make install PREFIX=$HOME/.local
script: |
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
  else
    BUSTED=$HOME/.luarocks/bin/busted
  fi
  make test BUSTED="$BUSTED"
